homeassistant:
  name: Home
  latitude: !secret homeassistant_latitude
  longitude: !secret homeassistant_longitude
  elevation: !secret homeassistant_elevation
  time_zone: !secret homeassistant_timezone
  unit_system: metric
  customize:
    switch.outdoor_1_switch:
      friendly_name: Roof Lining
    switch.outdoor_2_switch:
      friendly_name: Trees

frontend:

config:

http:
  base_url: !secret http_base_url
  ip_ban_enabled: true
  login_attempts_threshold: 3

updater:
  include_used_components: true

history:

logbook:

# mqtt used for smartbridge integration
# https://github.com/stjohnjohnson/smartthings-mqtt-bridge
mqtt:
  broker: !secret server_ip

sun:

tts:
  platform: google_translate

automation: !include_dir_merge_list automations
group: !include_dir_merge_named groups
sensor: !include_dir_merge_list sensors
script : !include_dir_merge_named scripts
switch: !include_dir_merge_list switches

ecobee:
  api_key: !secret ecobee_api_key

# garage
# https://github.com/stjohnjohnson/smartthings-mqtt-bridge/issues/38
# https://home-assistant.io/components/cover.mqtt/
cover:
  platform: mqtt
  name: 'Garage'
  state_topic: 'smartthings/Garage/contact'
  command_topic: 'smartthings/Garage/door'
  state_open: 'open'
  state_closed: 'closed'
  payload_open: 'open'
  payload_close: 'closed'
  retain: true
  optimistic: true

unifi:
  controllers:
    - host: !secret server_ip
      site: Default
      ssid_filter:
        - !secret wifi_ssid

discovery:

zwave:
  usb_path: /dev/zwave
  network_key: !secret zwave_network_key
  polling_interval: 30000
  debug: true
  autoheal: true

rachio:
  api_key: !secret switch_rachio_api_key
  hass_url_override: !secret server_url

tplink:
  discovery: false
  switch:
    - host: !secret switches_office_light_switch_host
    - host: !secret switches_office_plug_host
