homeassistant:
  name: Home
  latitude: !secret homeassistant_latitude
  longitude: !secret homeassistant_longitude
  elevation: !secret homeassistant_elevation
  time_zone: !secret homeassistant_timezone
  unit_system: metric
  customize:
    switch.outdoor_1_switch:
      friendly_name: Roof Lining
    switch.outdoor_2_switch:
      friendly_name: Trees
  # auth_providers:
  # - type: legacy_api_password
  # - type: homeassistant


frontend:

config:

http:
  api_password: !secret http_api_password
  base_url: !secret http_base_url
  ip_ban_enabled: true
  use_x_forwarded_for: true
  trusted_proxies:
    - !secret http_trusted_proxies_1
    - !secret http_trusted_proxies_2
    - !secret http_trusted_proxies_3
  login_attempts_threshold: 3

updater:
  include_used_components: true

history:

logbook:

# mqtt used for smartbridge integration
# https://github.com/stjohnjohnson/smartthings-mqtt-bridge
mqtt:
  broker: !secret server_ip

sun:

tts:
  platform: google

automation: !include_dir_merge_list automations
group: !include_dir_merge_named groups
sensor: !include_dir_merge_list sensors
script : !include_dir_merge_named scripts
switch: !include_dir_merge_list switches

# notifications
notify:
- name: pushetta
  platform: pushetta
  api_key: !secret notify_pushetta_api_key
  channel_name: !secret notify_pushetta_atomaka_channel_name

ecobee:
  api_key: !secret ecobee_api_key

# garage
# https://github.com/stjohnjohnson/smartthings-mqtt-bridge/issues/38
# https://home-assistant.io/components/cover.mqtt/
cover:
  platform: mqtt
  name: 'Garage'
  state_topic: 'smartthings/Garage/contact'
  command_topic: 'smartthings/Garage/door'
  state_open: 'open'
  state_closed: 'closed'
  payload_open: 'open'
  payload_close: 'closed'
  retain: true
  optimistic: true

device_tracker:
  - platform: unifi
    host: !secret server_ip
    port: 8443
    verify_ssl: false
    username: !secret device_tracker_unifi_username
    password: !secret device_tracker_unifi_password
    ssid_filter:
    - !secret wifi_ssid
    dont_track_devices: true

discovery:

zwave:
  usb_path: /dev/zwave
  network_key: !secret zwave_network_key
  polling_interval: 30000
  debug: true
  autoheal: true

rachio:
  api_key: !secret switch_rachio_api_key
  hass_url_override: !secret server_url
