title: Home
views:
  - path: default_view
    title: Home
    badges:
      - entity: person.andrew_tomaka
      - entity: person.stacey
      - entity: binary_sensor.living_room_occupancy
      - entity: binary_sensor.master_bedroom_occupancy
      - entity: binary_sensor.office_occupancy
      - entity: binary_sensor.main_floor_occupancy
    cards:
      - type: entities
        title: Doors
        entities:
          - lock.garage_lock_locked
          - cover.linear_nortek_security_control_llc_gd00z_4_garage_door_opener_remote_controller_barrier_state_label
      - type: entities
        title: Outside Lights
        entities:
          - switch.landscape_lights_switch
  - path: office
    title: Office
    cards:
      - type: entities
        entities:
          - switch.office_light
          - switch.office_plug
