- alias: Turn on Christmas lights at night
  trigger:
  - platform: state
    entity_id: sun.sun
    to: 'below_horizon'
    from: 'above_horizon'
  action:
    - service: homeassistant.turn_on
      entity_id: switch.outdoor_1_switch
    - service: homeassistant.turn_on
      entity_id: switch.outdoor_2_switch
    - service: homeassistant.turn_on
      entity_id: switch.christmas_tree
- alias: Turn off Christmas lights in day
  trigger:
    platform: time
    at: "01:00:00"
  action:
    - service: homeassistant.turn_off
      entity_id: switch.outdoor_1_switch
    - service: homeassistant.turn_off
      entity_id: switch.outdoor_2_switch
    - service: homeassistant.turn_off
      entity_id: switch.christmas_tree
