- alias: Garage open at night
  hide_entity: true
  trigger:
    - platform: time
      minutes: '/30'
      seconds: 00
  condition:
  - condition: and
    conditions:
      - condition: state
        entity_id: sun.sun
        state: 'below_horizon'
      - condition: template
        value_template: "{{ states('cover.garage') == 'open' }}"
  action:
    - service: notify.pushetta
      data:
        message: 'Garage door is open'
