- alias: Turn off office plug when office switch comes on
  hide_entity: true
  trigger:
    platform: state
    entity_id: switch.office_light_switch
    to: 'on'
    from: 'off'
  action:
    service: homeassistant.turn_off
    entity_id: switch.office_plug
- alias: Turn on office plug when office switch goes off
  hide_entity: true
  trigger:
    platform: state
    entity_id: switch.office_light_switch
    to: 'off'
    from: 'on'
  action:
    service: homeassistant.turn_on
    entity_id: switch.office_plug
