- alias: Turn on outdoor lights at night
  trigger:
  - platform: state
    entity_id: sun.sun
    to: 'below_horizon'
    from: 'above_horizon'
  action:
    service: homeassistant.turn_on
    entity_id: switch.landscape_lights_switch
- alias: Turn off outdoor lights in day
  trigger:
  - platform: state
    entity_id: sun.sun
    to: 'above_horizon'
    from: 'below_horizon'
  action:
    service: homeassistant.turn_off
    entity_id: switch.landscape_lights_switch
